curl "http://localhost:3007/api/osrm/route?startLat=-36.823271&startLon=-73.039517&endLat=-36.826818&endLon=-73.039560"

###
curl "http://localhost:3007/api/osrm/route?startLat=-36.823271&startLon=-73.039517&endLat=-36.614119&endLon=-72.959328"

### Aplicar el Hash a las contraseñas 
POST http://localhost:3007/api/admin/update-passwords

### Login de usuario
POST http://localhost:3007/api/users/login
Content-Type: application/json

{
  "usuario_correo": "cliente1@gmail.com",
  "usuario_password": "cliente123",
  "usuario_rol": 2
}
